version: '3.5'

services:

 zabbix-server:
  image: zabbix/zabbix-server-mysql:alpine-4.0-latest
  restart: always
  ports:
   - "${SERVER_PORT}:10051"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro 
   - ./zbx_env/server/alertscripts:/usr/lib/zabbix/alertscripts:ro
   - ./zbx_env/server/externalscripts:/usr/lib/zabbix/externalscripts:ro
   - ./zbx_env/server/modules:/var/lib/zabbix/modules:ro
   - ./zbx_env/server/enc:/var/lib/zabbix/enc:ro
   - ./zbx_env/server/ssh_keys:/var/lib/zabbix/ssh_keys:ro
   - ./zbx_env/server/mibs:/var/lib/zabbix/mibs:ro
   - ./zbx_env/server/snmptraps:/var/lib/zabbix/snmptraps:ro
   - ./zbx_env/server/log:/var/log:rw
  links:
   - mysql-server:mysql-server
  ulimits:
   nproc: 65535
   nofile:
    soft: 20000
    hard: 40000
#  deploy:
#   resources:
#    limits:
#      cpus: '0.70'
#      memory: 1G
#    reservations:
#      cpus: '0.5'
#      memory: 512M
  env_file:
   - ./conf/.env_db_mysql
   - ./conf/.env_srv
  user: root
  depends_on:
   - mysql-server
   - zabbix-snmptraps
  networks:
   zbx_net_backend:
     aliases:
      - zabbix-server
      - zabbix-server-mysql
      - zabbix-server-alpine-mysql
      - zabbix-server-mysql-alpine
   zbx_net_frontend:
#  devices:
#   - "/dev/ttyUSB0:/dev/ttyUSB0"
  stop_grace_period: 30s
  sysctls:
   - net.ipv4.ip_local_port_range=1024 65000
   - net.ipv4.conf.all.accept_redirects=0
   - net.ipv4.conf.all.secure_redirects=0
   - net.ipv4.conf.all.send_redirects=0
  labels:
   com.zabbix.description: "Zabbix server with MySQL database support"
   com.zabbix.company: "Zabbix SIA"
   com.zabbix.component: "zabbix-server"
   com.zabbix.dbtype: "mysql"
   com.zabbix.os: "alpine"

 zabbix-web-nginx-mysql:
  image: zabbix/zabbix-web-nginx-mysql:alpine-4.0-latest
  restart: always
  ports:
   - "${WEB_HTTP}:80"
   - "${WEB_HTTPS}:443"
  links:
   - mysql-server:mysql-server
   - zabbix-server:zabbix-server
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - ./zbx_env/web/nginx:/etc/ssl/nginx:ro
   - ./zbx_env/web/log:/var/log:rw
#  deploy:
#   resources:
#    limits:
#      cpus: '0.70'
#      memory: 512M
#    reservations:
#      cpus: '0.5'
#      memory: 256M
  env_file:
   - ./conf/.env_db_mysql
   - ./conf/.env_web
  user: root
  depends_on:
   - mysql-server
   - zabbix-server
  healthcheck:
   test: ["CMD", "curl", "-f", "http://localhost"]
   interval: 10s
   timeout: 5s
   retries: 3
   start_period: 30s
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-web-nginx-mysql
     - zabbix-web-nginx-alpine-mysql
     - zabbix-web-nginx-mysql-alpine
   zbx_net_frontend:
  stop_grace_period: 10s
  sysctls:
   - net.core.somaxconn=65535
  labels:
   com.zabbix.description: "Zabbix frontend on Nginx web-server with MySQL database support"
   com.zabbix.company: "Zabbix SIA"
   com.zabbix.component: "zabbix-frontend"
   com.zabbix.webserver: "nginx"
   com.zabbix.dbtype: "mysql"
   com.zabbix.os: "alpine"

 zabbix-agent:
  image: zabbix/zabbix-agent:alpine-4.0-latest
  restart: always
  ports:
   - "${AGENT_PORT}:10050"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - ./zbx_env/agent/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
   - ./zbx_env/agent/modules:/var/lib/zabbix/modules:ro
   - ./zbx_env/agent/enc:/var/lib/zabbix/enc:ro
   - ./zbx_env/agent/ssh_keys:/var/lib/zabbix/ssh_keys:ro
   - ./zbx_env/agent/log:/var/log:rw
  links:
   - zabbix-server:zabbix-server
#  deploy:
#   resources:
#    limits:
#      cpus: '0.2'
#      memory: 128M
#    reservations:
#      cpus: '0.1'
#      memory: 64M
#   mode: global
  env_file:
   - ./conf/.env_agent
  user: root
  privileged: true
  pid: "host"
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-agent
     - zabbix-agent-passive
     - zabbix-agent-alpine
  stop_grace_period: 5s
  labels:
   com.zabbix.description: "Zabbix agent"
   com.zabbix.company: "Zabbix SIA"
   com.zabbix.component: "zabbix-agentd"
   com.zabbix.os: "alpine"

 zabbix-snmptraps:
  image: zabbix/zabbix-snmptraps:alpine-4.0-latest
  restart: always
  ports:
   - "162:162/udp"
  volumes:
   - ./zbx_env/snmp/snmptraps:/var/lib/zabbix/snmptraps:rw
   - ./zbx_env/snmp/log:/var/log:rw
#  deploy:
#   resources:
#    limits:
#      cpus: '0.5'
#      memory: 256M
#    reservations:
#      cpus: '0.25'
#      memory: 128M
  user: root
  networks:
   zbx_net_frontend:
    aliases:
     - zabbix-snmptraps
   zbx_net_backend:
  stop_grace_period: 5s
  labels:
   com.zabbix.description: "Zabbix snmptraps"
   com.zabbix.company: "Zabbix SIA"
   com.zabbix.component: "snmptraps"
   com.zabbix.os: "ubuntu"

 mysql-server:
  image: mysql:5.7
  restart: always
  command: [mysqld, --character-set-server=utf8, --collation-server=utf8_bin]
  volumes:
   - ./zbx_env/mysql/mysql:/var/lib/mysql:rw
   - ./zbx_env/mysql/log:/var/log:rw
  env_file:
   - ./conf/.env_db_mysql
  user: root
  stop_grace_period: 1m
  networks:
   zbx_net_backend:
    aliases:
     - mysql-server
     - zabbix-database
     - mysql-database

networks:
  zbx_net_frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
  zbx_net_backend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24
